config/routes.rb
Rails.application.routes.draw do
  root "homes#show"
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resource :dashboard, only: [:show]
  
  resources :subreddits, only: [:index, :create, :destroy]
  resources :subreddit_searches, only: [:create]

  namespace :link do
    resource :retrievals, only: [:show, :create]
    resources :searches, only: [:create, :update]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :tracks, only: [:create, :update, :destroy]
  end

  resources :votes, only: [:update]
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :user, counter_cache: true, touch: true

  validates_length_of :title, maximum: 255
  validates_length_of :name, maximum: 255
  validates_numericality_of :score, only_integer: true, on: :create
  validates_numericality_of :first_score, only_integer: true, on: :create
  validates_numericality_of :target_score, only_integer: true, on: :create

  validate :existing_track, on: :create

  def existing_track
    if Track.exists?(name: self.name, user_id: self.user_id)
      errors.add(:base, "You are already tracking this")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :recoverable, :validatable, :trackable,

  devise :database_authenticatable, :registerable,
          :rememberable, :omniauthable

  has_many :tracks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :refresh_reddit_token

  def refresh_reddit_token
    RefreshRedditToken.run(current_user) if user_signed_in?
  end

  def only_respond_to_ajax
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.js   {}
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    @dashboard = DashboardFacade.new(current_user)
    pass_data_to_js
  end

  private

  def pass_data_to_js
    gon.subreddits_path = subreddits_path
    gon.links_path      = link_retrievals_path
    gon.user_id         = current_user.id
    gon.user_tracks     = @dashboard.track_names_array
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    if user_signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/link/retrievals_controller.rb
class Link::RetrievalsController < ApplicationController
  before_action :authenticate_user!, :only_respond_to_ajax
  
  def show
    @links = LinkFacade.new(current_user, get_sub)
  end

  def create 
    @link = Reddit::FetchPostViaUrl.run(current_user, params[:path])
    @track = current_user.tracks.new
  end
  
  private

  def get_sub
    if params.has_key?(:subreddit)
      params[:subreddit]
    else
      nil
    end
  end
end

app/controllers/link/retrieves_controller.rb
class Link::RetrievesController < ApplicationController
  def show
    @dashboard = Dashboard.new(current_user)
  end

  def create 
    @link = Reddit::LinkViaUrl.new(current_user, params[:path]).retrieve
    @track = current_user.tracks.new
  end
end

app/controllers/link/searches_controller.rb
class Link::SearchesController < ApplicationController
  before_action :authenticate_user!, :only_respond_to_ajax

  def create
    @search = Reddit::LinksSearch.new(current_user, params[:search])
  end

  def update
    @search_update = Reddit::LinksSearch.new(current_user, params[:update], params[:id])
  end
end

app/controllers/link_searches_controller.rb
class LinkSearchesController < ApplicationController
  before_action :authenticate_user!, :only_respond_to_ajax

  def create
    @search = Reddit::LinksSearch.new(current_user, params[:search])
  end

  def update
    @search_update = Reddit::LinksSearch.new(current_user, params[:update], params[:id])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def reddit
    @user = GetUserFromOmniauth.run(request.env["omniauth.auth"])

    sign_in_and_redirect @user, :event => :authentication 
    flash[:success] = "signin"
  end
end

app/controllers/subreddit_searches_controller.rb
class SubredditSearchesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_respond_to_ajax

  def create
    @search = Reddit::SubSearch.new(current_user, params[:search])
  end
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :authenticate_user!
  before_action :only_respond_to_ajax
  
  def index
    @subreddit = SubredditFacade.new(current_user)
  end

  def create
    @subreddit = Reddit::SubSubscribe.new(current_user, params[:subreddit])
  end

  def destroy
    @subreddit = Reddit::SubUnsubscribe.new(current_user, params[:id])
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :authenticate_user!, :only_respond_to_ajax
  
  def index
    @subreddit = SubredditFacade.new(current_user)
  end

  def create
    @subreddit = Reddit::SubSubscribe.new(current_user, params[:subreddit])
  end

  def destroy
    @subreddit = Reddit::SubUnsubscribe.new(current_user, params[:id])
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!
  before_action :only_respond_to_ajax

  def create
    @track = create_track
  end

  def update
    @track = Reddit::UpdateTrackData.new(current_user, params[:id]).process
  end

  def destroy
    @track = destroy_track
  end

  private

  def create_track
    current_user.tracks.create(track_params)
  end

  def destroy_track
    current_user.tracks.find(params[:id]).destroy
  end

  def track_params
    params.require(:track).permit(:title, :name, :score, :first_score, :target_score, :permalink)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def edit
    @dashboard = DashboardFacade.new(current_user)
    pass_data_to_js
  end

  def update
    current_user.update_attributes(user_params)
    only_respond_to_ajax
  end

  private

  def pass_data_to_js
    gon.user_id = current_user.id
    gon.user_tracks = @dashboard.track_names_array
  end

  def user_params
    params.require(:user).permit(:email, :notify_me)
  end
end 

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!, :only_respond_to_ajax

  def update
    @link = Reddit::VoteUpLink.new(current_user, params[:id]).process
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def div_id(name, id)
    "id=#{name}_#{id}"
  end

  def div_id_s(name, id)
    "#{name}_#{id}"
  end

  def url_from_permalink(permalink)
    "http://www.reddit.com#{permalink}"
  end

  def vote_up_link(link)
    if link.attributes[:likes].nil?
      generate_vote_btn(link)
    else
      '<i class="icon-thumbs-up"></i>'.html_safe
    end
  end

  def check_link_tracking(user_tracks, link)
    'class=hide' unless user_tracks.include?(link.full_name)
  end

  def check_link_tracked(user_tracks, link)
    'class=hide' if user_tracks.include?(link.full_name)
  end

  def check_hit_target(track)
    if track.score >= track.target_score
      'hit_target'
    else
      check_rise_or_fall(track)
    end
  end

  def get_search_header(sub,term)
    if sub.blank?
      "Links from all subs #{get_search_term(trim_content(term, 50))}".html_safe
    else
      "Links from /r/#{sub}#{get_search_term(trim_content(term, 50))}".html_safe
    end
  end

  def trim_content(text, limit)
    TrimContentWithWords.run(text, limit) unless text.blank?
  end

  def bootstrap_class_for flash_type
    if flash_type == 'alert'
      'alert-danger'
    else
      'alert-success'
    end
  end

  private

  def get_search_term(term)
    if term.blank?
      ''
    else
      " for '<b>#{term}</b>'"
    end
  end

  def check_rise_or_fall(track)
    if track.score >= track.first_score
      'rising'
    else
      'falling'
    end
  end

  def generate_vote_btn(link)
    link_to(vote_path(id: link.full_name), method: :put, title: "Up-vote", remote: true) do
      '<i class="quick_hide icon-arrow-up"></i>'.html_safe
    end
  end
end

app/views/dashboards/_subscribed_subs.html.erb
<div id="subscribed_subs">
  <% subs.each do |sub| %>
    <div id="sub_<%= sub.full_name %>">
      <%= sub.name %>&nbsp;&nbsp;
      <%= link_to sub_path(:id => sub.full_name), method: :delete, :remote => true do %>
      <i class="icon-remove" onclick="quick_hide_parent(this);"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/dashboards/show.html.erb
<div class="row">
  <div class="col-md-8 col-xs-12">
    <div class="widget" data-step="1" data-intro="This is where you can search for relevant reddit posts.">
      <div class="widget-header"> 
        <i class="icon-plane"></i>
        <h3>Search Reddit</h3>
      </div>
      
      <div class="widget-content">
        <div id="links_search">
          <%= render 'shared/search_filter' %>
        </div>
      </div>  
    </div> 

    <div class="widget" data-step="2" data-intro="All the links from reddit will be displayed here.">
      <div class="widget-header"> 
        <i class="icon-list"></i>
        <h3 id="results_header">Reddit front page</h3>
      </div>
      
      <div class="widget-content">
        <div id="links_loading" class="center">
          <%= image_tag "ajax-loader.gif" %>
        </div> 
        <div id="links_content">
        </div> 
        <div id="links_more">  
        </div>
      </div>  
    </div> 
  </div>

  <%= render 'shared/subs_and_tracks' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RedditTrack" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= include_gon %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
  </head>
  <body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">Reddit Track</a>
      </div>

      <%= render 'shared/navbar' %>

    </div> <!-- /container -->
  </nav>
    
  <div class="main">
      <div id="main_outer" class="container">
        <%= render 'shared/custom_flash' %>
        <%= yield %>
      </div> <!-- /container -->
  </div> <!-- /main -->
  
    
  <div class="footer">
    <div class="container">
      <div class="row">
        <div id="footer-copyright" class="col-md-6">
          Reddit Track. A prototype from Richard Lamb
        </div> <!-- /span6 -->
      </div> <!-- /row -->
    </div> <!-- /container -->
  </div> <!-- /footer -->

  </body>
</html>

app/views/link/_via_url.html.erb
<div>
  <%= form_tag(link_retrievals_path, remote: true, class: "") do |form| %>
    <%= text_field_tag :path, nil, class: "inputpad large_input", placeholder: "Enter a reddit post URL here..." %>
    <%= submit_tag "Submit", class: "btn btn-info", data: { disable_with: "Working..." } %>
  <% end %>
</div>
<div id="link_via_url_content"></div>

app/views/link/searches/create.js.erb
// Change results header to reflect latest search
$('#results_header').html('<%= j get_search_header(params[:search][:subreddit],params[:search][:term]) %>');

stop_search_loading();

// Place results into appropriate div
$("#links_content").html("<%= j render 'shared/reddit_links', links: @search.links_by_term, :track => @search.build_track, user_tracks: @search.track_names_array %>");

//links_more
$("#links_more").html("<%= j render 'shared/show_more', links: @search.links_by_term, update: params[:search] %>");

bind_popovers_on_links();
bind_quick_hides();

app/views/link/searches/update.js.erb
// Place results into appropriate div
$("#links_table tr:last").after("<%= j render 'shared/reddit_link_rows', links: @search_update.links_by_term, :track => @search_update.build_track, user_tracks: @search_update.track_names_array %>");

//links_more
$("#links_more").html("<%= j render 'shared/show_more', links: @search_update.links_by_term, update: params[:update] %>");

bind_popovers_on_links();
bind_quick_hides();

app/views/shared/_custom_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert fade in <%= bootstrap_class_for(type) %> alert-dismissable">
    <button aria-hidden="true" class="close" data-dismiss="alert" type="button">X</button> 
    <% if message == 'signin' %>
      You have successfully signed in via Reddit. 

      <% if user_signed_in? && current_user.tracks_count == 0 %>
      <button id="start_tour" class="btn btn-info sml">Start the Tour</button>
      <% end %>
    <% else %>
      <%= message %>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
    <li class="dropdown">
      <a href="javscript:;" class="dropdown-toggle" data-toggle="dropdown">
        <i class="icon-cog"></i>
        Settings
        <b class="caret"></b>
      </a>
      
      <ul class="dropdown-menu">
        <li><%= link_to "Notification Settings", edit_user_path(current_user) %></li>
      </ul>
    </li>


    <li class="dropdown">
          
    <a href="javscript:;" class="dropdown-toggle" data-toggle="dropdown">
      <i class="icon-user"></i> 
      <%= current_user.name %>
      <b class="caret"></b>
    </a>
    
    <ul class="dropdown-menu">
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>   </li>
    </ul> 
  </li>
  <% else %>
    <li><%= link_to "Sign in with your Reddit Account", omniauth_authorize_path(:user, :reddit) %> </li>
  <% end %>
  </ul>
</div> <!-- /navbar-ex1-collapse -->

app/views/shared/_reddit_link_rows.html.erb
<% links.each_with_index do |link, index| %>
<tr <% if index == 0 %>data-step="3" data-intro="Here you can upvote the link, see it's current score, click the title to visit the page on reddit and track it using the button on the right."<% end %>>
  <td <%= div_id('link_vote', link.full_name) %> class="text-center">
    <%= vote_up_link(link) %>
  </td>
  <td class="link_score center">
    <%= link.attributes[:score] %></td>
  <td>
    <span class="link_title">
      <%= link_to trim_content(link.title, 160), url_from_permalink(link.attributes[:permalink]), target: "_blank" %>
    </span>
    <div class="link_details">
        <%= time_ago_in_words(Time.at(link.attributes[:created_utc]).localtime) %> ago 
        by <%= link.author %>.&nbsp;&nbsp;
        <%= link.attributes[:num_comments] %> <i class="icon-comment light"></i> 
    </div>
  </td>
  <td <%= div_id('link_tracking', link.full_name) %>>
    <div <%= div_id('link_tracked', link.full_name) %> <%= check_link_tracking(user_tracks, link) %>>
      <%= render 'tracks/track_added' %>
    </div>
    <div <%= div_id('link_track_form', link.full_name) %> <%= check_link_tracked(user_tracks, link) %>>
      <div class="popover-markup center"> <%= button_tag "Track", class: "btn btn-info smt trigger" %>
          <div class="head hide">Track this link</div>
          <div class="content hide">
              <%= render 'tracks/new_track', link: link, track: track %>
          </div>
      </div>
    </div>
  </td>
</tr>
<% end %>

app/views/shared/_reddit_links.html.erb
<% if links.results.size > 0 %>
  <table id="links_table" class="table">
    <thead>
      <tr>
        <th></th>
        <th>Score</th>
        <th>Content</th>
        <th>Track</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'shared/reddit_link_rows', links: links, track: track, user_tracks: user_tracks %>
    </tbody>
  </table>
<% else %>
  Sorry no results were returned. Please try tweaking your search paramters.
<% end %>

app/views/shared/_search_filter.html.erb
<div class="row">
  <div class="col-md-12 col-xs-12">
    <%= form_tag(link_searches_path, method: :post, class: "form-inline", "role" => "form", remote: true) do |form| %>
      <div id="subs_search_select" class="form-group search_pd">
        <label class="sr-only" for="search_subreddit">Select Subreddit</label>
        <span class="bold">In</span>:&nbsp;&nbsp;<%= select_tag 'search[subreddit]', options_for_select([ "All Subreddits"]) %>
      </div>
      <div class="form-group search_pd">
        <label class="sr-only" for="search_sort">Search Type</label>
        <span class="bold">By:</span>&nbsp;&nbsp;<%= select_tag 'search[sort]', options_for_select([['Relevance', "relevance"], ['New', "new"], ['Hot', "hot"], ['Top', "top"]]) %>
      </div>
      <div class="form-group search_pd">
        <label class="sr-only" for="search_time">Date Range</label>
        <span class="bold">When:</span>&nbsp;&nbsp;<%= select_tag 'search[time]', options_for_select([['Day', "day"], ['Week', "week"], ['Month', "month"], ['Hour', "hour"]]) %>
      </div>
      <div class="form-group search_pd">
        <label class="sr-only" for="search_term">Search Term</label>
        <%= text_field_tag 'search[term]', nil, placeholder: 'Enter search term...', class: "inputpad med_input" %>  
      </div>
      <div class="form-group search_pd">
        <%= submit_tag "Search", id: "link_search_btn", class: "btn btn-info", data: { disable_with: "Working..." } %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_search_subs.html.erb
Search Subs
<%= form_tag(subreddit_searches_path, method: :post, remote: true, class: "tmt") do |form| %>
  <%= text_field_tag :search, nil, class: "inputpad click_clear", placeholder: "Enter search term..." %>
  <%= submit_tag "Search", class: "btn btn-info", data: { disable_with: "Working..." } %>
<% end %>
<div id="subreddit_search_results" class="smt hide">

</div>

app/views/shared/_show_more.html.erb
<% if links.results.size == 25 %>
<div class="center">
  <%= form_tag(link_search_path(id: links.results.last.full_name), method: :put, remote: true) do |form| %>
    <%= hidden_field_tag 'update[subreddit]', update[:subreddit] %>
    <%= hidden_field_tag 'update[sort]', update[:sort] %>
    <%= hidden_field_tag 'update[time]', update[:time] %>
    <%= hidden_field_tag 'update[term]', update[:term] %>

    <%= submit_tag "Show More", class: "btn btn-info", data: { disable_with: "Working..." } %>
  <% end %>
</div>
<% end %>

app/views/shared/_subs_and_tracks.html.erb
<div class="col-md-4 col-xs-12">
  <div class="widget" data-step="6" data-intro="Or add a track via URL" data-position="left">
    <div class="widget-header"> 
      <i class="icon-plane"></i>
      <h3>Track via URL</h3>
    </div>
    
    <div class="widget-content">
      <%= render 'link/via_url' %>
    </div>  
  </div>  

  <div class="widget" data-step="4" data-intro="All links you are tracking will display here. Scores update in real time every 10 seconds (one link per update)" data-position="left">
    <div class="widget-header"> 
      <i class="icon-star"></i>
      <h3>My Tracks</h3>
    </div>
    
    <div class="widget-content">
      <%= render 'shared/tracks', tracks: @dashboard.user_tracks %>
    </div>  
  </div>  
  <div class="widget" data-step="5" data-intro="If you want to add a new subreddit to the search filter, this is the place to do it."  data-position="left">
    <div class="widget-header"> 
      <i class="icon-bookmark"></i>
      <h3>My SubReddits</h3>
    </div>
    
    <div class="widget-content">
      <%= render 'shared/search_subs' %><br>
      <div id="subs_loading" class="center">
          <%= image_tag "ajax-loader.gif" %>
        </div> 
      <div id="subscribed_subs_outer">
      </div>
    </div>  
  </div>  
</div>

app/views/shared/_subscribed_subs.html.erb
<div id="subscribed_subs">
  <% subreddits.each do |subreddit| %>
    <div <%= div_id('subreddit', subreddit.full_name) %>>
      <%= link_to subreddit.name, { controller: "link/retrievals", action: :show, subreddit: subreddit.name }, class: 'user_sub', remote: true %>&nbsp;&nbsp;
      <%= link_to subreddit_path(:id => subreddit.full_name), method: :delete, :remote => true do %>
      <i class="icon-remove quick_hide_parent"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_tracks.html.erb
<table id="tracks_content" class="table">
  <thead>
    <th style="width: 20%">
      Score
    </th>
    <th>
      Title
    </th>
    <th style="width: 20%">
      Target
    </th>
    <th>
    &nbsp;
    </th>
  </thead>
  <tbody>
  <% if current_user.tracks_count > 0 %>
    <%= render tracks %>
  <% else %>
    <tr><td id="links_nolinks" colspan="3">You aren't tracking any links yet.</td></tr>
  <% end %>
  </tbody>
</table>

<script>
  $("#tracks_content").tablesorter({ 
      headers: {  
          3: { 
              sorter: false 
          } 
      } 
  });
</script>

app/views/sub_searches/_sub_search_result.html.erb
<div>
  <%= form_tag(subs_path, method: :post, remote: true) do |form| %>
    <%= hidden_field_tag :subreddit, sub.full_name %>

    <% if !subscribed %> 
      <span class="bold"><%= sub.display_name %></span>&nbsp;&nbsp;<i class="iconhover icon-arrow-right hide_and_submit"></i> 
    <% else %>
      <%= sub.display_name %>
    <% end %>
  <% end %>
</div>

app/views/sub_searches/create.js.erb
$('#sub_search_results').html('').removeClass('hide');

<% if @search.search_subs_by_name.count == 0 %>
  $('#sub_search_results').html('No matches found.');
<% else %>
  <% @search.search_subs_by_name.take(5).each do |sub| %>
    // if not already subscribed, add to results
    if($('#<%= div_id_s("sub", sub.full_name) %>').length == 0)
    {
      $('#sub_search_results').append("<%= j render 'sub_searches/sub_search_result', sub: sub, subscribed: false %>");
    }
    else
    {
      $('#sub_search_results').append("<%= j render 'sub_searches/sub_search_result', sub: sub, subscribed: true %>");
    }
  <% end %>
<% end %>

bind_hide_and_submit();

app/views/subreddit_searches/_search_result.html.erb
<div>
  <%= form_tag(subreddits_path, method: :post, remote: true) do |form| %>
    <%= hidden_field_tag :subreddit, sub.full_name %>

    <% if !subscribed %> 
      <span class="bold"><%= sub.display_name %></span>&nbsp;&nbsp;<i class="iconhover icon-arrow-right hide_and_submit"></i> 
    <% else %>
      <%= sub.display_name %>
    <% end %>
  <% end %>
</div>

app/views/subreddit_searches/_sub_search_result.html.erb
<div>
  <%= form_tag(subreddits_path, method: :post, remote: true) do |form| %>
    <%= hidden_field_tag :subreddit, sub.full_name %>

    <% if !subscribed %> 
      <span class="bold"><%= sub.display_name %></span>&nbsp;&nbsp;<i class="iconhover icon-arrow-right hide_and_submit"></i> 
    <% else %>
      <%= sub.display_name %>
    <% end %>
  <% end %>
</div>

app/views/subreddit_searches/create.js.erb
$('#subreddit_search_results').html('').removeClass('hide');

<% if @search.search_subs_by_name.count == 0 %>
  $('#subreddit_search_results').html('No matches found.');
<% else %>
  <% @search.search_subs_by_name.take(5).each do |sub| %>
    // if not already subscribed, add to results
    if($('#<%= div_id_s("sub", sub.full_name) %>').length == 0)
    {
      $('#subreddit_search_results').append("<%= j render 'subreddit_searches/search_result', sub: sub, subscribed: false %>");
    }
    else
    {
      $('#subreddit_search_results').append("<%= j render 'subreddit_searches/search_result', sub: sub, subscribed: true %>");
    }
  <% end %>
<% end %>

bind_hide_and_submit();

app/views/subreddits/_search_select.html.erb
<label class="sr-only" for="search_subreddit">Select Subreddit</label>
<span class="bold">In</span>:&nbsp;&nbsp;<%= select_tag 'search[subreddit]', options_for_select(subreddits), {prompt: "All Subreddits"} %>

app/views/subreddits/create.js.erb
// Update user subs list
$('#subscribed_subs').html("<%= j render 'shared/subscribed_subs', subreddits: @subreddit.user_subscribed_subs %>");

// Update search filter with new subs
$('#links_search').html("<%= j render 'shared/search_filter', subreddits: @subreddit.subs_for_search %>");

bind_quick_hides();
bind_sub_searches();

app/views/subreddits/destroy.js.erb
// Update user subs list
$('#subscribed_subs').html("<%= j render 'shared/subscribed_subs', subreddits: @subreddit.user_subscribed_subs %>");

// Update search filter with new subs
$('#links_search').html("<%= j render 'shared/search_filter', subreddits: @subreddit.subs_for_search %>");

bind_quick_hides();
bind_sub_searches();

app/views/subreddits/index.js.erb
$('#subscribed_subs_outer').html("<%= j render 'shared/subscribed_subs', subreddits: @subreddit.subscribed_subs %>");
$('#subs_search_select').html("<%= j render 'subreddits/search_select', subreddits: @subreddit.subs_for_search %>");
$('#subs_loading').hide();

bind_sub_searches();

app/views/tracks/_track.html.erb
<tr <%= div_id('track', track.id) %>>
  <td <%= div_id('track_score_col', track.id) %>>
    <div <%= div_id('track_score', track.id) %> class="link_score <%= check_hit_target(track) %>">
      <%= track.score %>
    </div> 
  </td>
  <td>
    <%= link_to trim_content(track.title, 50), url_from_permalink(track.permalink), target: "_blank", title: track.title %>
  </td>
  <td class="link_score">
    <%= track.target_score %> 
  </td>
  <td>
    <%= link_to user_track_path(current_user, track), method: :delete, data: { confirm: "Do you really want to delete this track?"}, :remote => true  do %>
      <i class="icon-remove"></i>
    <% end %>
  </td>
</tr>

app/views/tracks/_track_added.html.erb
<div class="smt center">
  <i class="icon-magic"></i>
</div>